name: Shorebird Patch

on:
  workflow_dispatch:
    inputs:
      target_platform:
        description: 'Target platform'
        required: true
        default: 'android'
        type: choice
        options:
          - android
          - ios
          - all

jobs:
  patch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Shorebird
        uses: shorebirdtech/setup-shorebird@v1

      - name: Shorebird Patch
        run: shorebird patch ${{ inputs.target_platform }}
        env:
          SHOREBIRD_TOKEN: ${{ secrets.SHOREBIRD_TOKEN }}
